steps:
  # Сборка Docker-образа для фронтенда
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/next-app', '-f', 'Dockerfile.fe', '.']

  # Загрузка Docker-образа в Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/next-app']

  # Развертывание приложения на Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'next-app', '--image', 'gcr.io/$PROJECT_ID/next-app', '--region', 'europe-north1', '--platform', 'managed', '--allow-unauthenticated']
